from collections.abc import Sequence


MODERATED_TEXT_FIELDS: dict[str, Sequence[str]] = {
    "POST /api/auth/register": ("username",),
    "PUT /api/auth/profile": ("display_name", "bio"),
    "POST /api/posts": ("content",),
    "PUT /api/posts/{post_id}": ("content",),
    "POST /api/posts/{post_id}/comments": ("content",),
    "PUT /api/comments/{comment_id}": ("content",),
    "POST /api/chat/conversations/{conversation_id}/messages": ("content",),
    "WS send_message": ("content",),
    "POST /api/communities": ("name", "description", "rules"),
    "PATCH /api/communities/{community_id}": ("name", "description", "rules"),
    "POST /api/communities/{community_id}/join": ("message",),
    "POST /api/communities/{community_id}/announcements": ("title", "content"),
    "PATCH /api/communities/{community_id}/announcements/{announcement_id}": (
        "title",
        "content",
    ),
    "POST /api/communities/{community_id}/bans": ("reason",),
    "POST /api/communities/{community_id}/chat/messages": ("content",),
    "POST /api/comic/events": (
        "name",
        "venue",
        "ticket_info",
        "website",
        "intro",
    ),
    "PUT /api/comic/events/{event_id}": (
        "name",
        "venue",
        "ticket_info",
        "website",
        "intro",
    ),
    "POST /api/comic/events/{event_id}/comments": ("content",),
    "POST /api/roles/apply": (
        "reason",
        "application_text",
        "contact_info",
        "extra_note",
        "portfolio_links[]",
    ),
    "PUT /api/roles/profiles/coser": (
        "cosname",
        "bio",
        "styles",
        "city",
        "social_links",
    ),
    "PUT /api/roles/profiles/photographer": (
        "equipment",
        "styles",
        "city",
        "social_links",
    ),
    "PUT /api/roles/profiles/service": (
        "service_type",
        "description",
        "city",
        "price_info",
    ),
    "POST /api/roles/applications/{application_id}/approve": ("review_comment",),
    "POST /api/roles/applications/{application_id}/reject": ("review_comment",),
    "POST /api/roles/applications/{application_id}/suspend": ("review_comment",),
    "POST /role-applications/{application_id}/approve": ("review_comment",),
    "POST /role-applications/{application_id}/reject": ("review_comment",),
    "POST /role-applications/{application_id}/suspend": ("review_comment",),
    "POST /api/topics": ("name", "description"),
    "PUT /api/topics/{topic_id}": ("description",),
    "POST /api/reports": ("reason",),
    "POST /api/reports/post": ("reason",),
    "POST /api/reports/comment": ("reason",),
    "POST /api/reports/user": ("reason",),
}


EXCLUDED_TEXT_INPUTS: dict[str, tuple[str, ...]] = {
    "POST /api/auth/register": ("email", "password", "email_code"),
    "POST /api/auth/login": ("login", "email", "password", "email_code"),
    "POST /api/auth/change-password": ("old_password", "new_password"),
    "POST /api/auth/forgot-password": ("email",),
    "POST /api/auth/reset-password": ("email", "email_code", "new_password"),
    "message media metadata": (
        "media_url",
        "avatar_url",
        "banner_url",
        "cover_photo_url",
    ),
    "role media evidence": ("proof_images", "portfolio_images"),
    "read-only queries": ("keyword", "search_query", "pagination", "sort"),
    "system-generated text": (
        "friend_acceptance_hi",
        "community_welcome_message",
        "notification_text",
        "recall_notice",
    ),
}
