"""add_community_chat_fields

Revision ID: 4a741a79120c
Revises: 42e2cad61b65
Create Date: 2026-06-20 04:07:34.838831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a741a79120c'
down_revision: Union[str, Sequence[str], None] = '42e2cad61b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('type', sa.String(length=20), nullable=True))
    # 现有一对一私信行设 type='direct'
    op.execute("UPDATE conversations SET type='direct' WHERE type IS NULL")
    op.add_column('conversations', sa.Column('community_id', sa.Integer(), nullable=True))
    op.alter_column('conversations', 'user1_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('conversations', 'user2_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index('ix_conversations_type', 'conversations', ['type'], unique=False)
    op.create_foreign_key('fk_conversations_community', 'conversations', 'communities', ['community_id'], ['id'])
    op.add_column('messages', sa.Column('deleted_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted_by_admin')
    op.drop_constraint('fk_conversations_community', 'conversations', type_='foreignkey')
    op.drop_index('ix_conversations_type', table_name='conversations')
    op.alter_column('conversations', 'user2_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('conversations', 'user1_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('conversations', 'community_id')
    op.drop_column('conversations', 'type')
    # ### end Alembic commands ###
