"""add_community_module

Revision ID: 42e2cad61b65
Revises: 2b925e82a6da
Create Date: 2026-06-20 01:11:52.756854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e2cad61b65'
down_revision: Union[str, Sequence[str], None] = 'c2e96a3103aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('banner_url', sa.String(length=255), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('join_policy', sa.String(length=20), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_communities_owner'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='fk_communities_topic'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_communities_slug')
    )
    op.create_index(op.f('ix_communities_owner_id'), 'communities', ['owner_id'], unique=False)
    op.create_index('ix_communities_topic', 'communities', ['topic_id'], unique=False)
    op.create_table('community_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name='fk_cjr_community', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='fk_cjr_reviewer'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_cjr_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='uq_cjr_community_user')
    )
    op.create_table('community_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name='fk_cm_community', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_cm_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='uq_cm_community_user')
    )
    op.create_index('ix_cm_community_role', 'community_members', ['community_id', 'role'], unique=False)
    op.create_index('ix_cm_user_status', 'community_members', ['user_id', 'status'], unique=False)
    op.add_column('posts', sa.Column('community_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('community_only', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('hidden_by_admin', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('hidden_by', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('hidden_at', sa.DateTime(), nullable=True))
    op.create_index('ix_posts_community_created', 'posts', ['community_id', 'created_at'], unique=False)
    op.create_foreign_key('fk_posts_hidden_by', 'posts', 'users', ['hidden_by'], ['id'])
    op.create_foreign_key('fk_posts_community', 'posts', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_posts_community', 'posts', type_='foreignkey')
    op.drop_constraint('fk_posts_hidden_by', 'posts', type_='foreignkey')
    op.drop_index('ix_posts_community_created', table_name='posts')
    op.drop_column('posts', 'hidden_at')
    op.drop_column('posts', 'hidden_by')
    op.drop_column('posts', 'hidden_by_admin')
    op.drop_column('posts', 'community_only')
    op.drop_column('posts', 'community_id')
    op.drop_index('ix_cm_user_status', table_name='community_members')
    op.drop_index('ix_cm_community_role', table_name='community_members')
    op.drop_table('community_members')
    op.drop_table('community_join_requests')
    op.drop_index('ix_communities_topic', table_name='communities')
    op.drop_index(op.f('ix_communities_owner_id'), table_name='communities')
    op.drop_table('communities')
    # ### end Alembic commands ###
